### ISSUE TITLE
As an Analyst, I want to validate administrative info

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-ciip-portal#1925]
CAS checks the administrative information against what is listed on the orgbook and corporate registry numbers.

AC
(in metabase)
- [x] Metabase dashboard includes check #1 as per Hanna's comment
- [x] Metabase dashboard includes check #2 as per Hanna's comment
- [x] Metabase dashboard includes check #3 as per Hanna's comment

**Comment by hannavovk** [comment]
Our Admin check include:

1. Legal name and BC Corporate Registry number need to align. As we are making an assumption that these have been checked and aligned last year, we compare these to last year's data.
2. Check that BCGHGID exists for facility.
3. Check if NAICS code has changed since last year.

All Admin checks return a flag for the reviewer, not necessarily a  comment. If there's a flag, reviewer then needs to investigate further and determine if a comment is warranted.

**Comment by Dianadec** [comment]
Looks like this one just needs an estimate.

**Comment by matthieu-foucault** [comment]
@dleard @pbastia @naomiaro Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-ciip-portal/1925?planning-poker)

**Comment by pbastia** [comment]
see @dleard 's question about "latest reporting year" to join on to get the applications
